WINDOW_WIDTH = 960
WINDOW_HEIGHT = 720
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT
WINDOW_CENTER = WINDOW_WIDTH//2, WINDOW_HEIGHT//2

SCALED_WINDOW_WIDTH = 960
SCALED_WINDOW_HEIGHT = 720
SCALED_WINDOW_SIZE = SCALED_WINDOW_WIDTH, SCALED_WINDOW_HEIGHT

WINDOW_SCALE = SCALED_WINDOW_WIDTH/WINDOW_WIDTH

CAPTION = "Filmore's Island"
FRAMERATE = 100

SHOW_DEBUG = False